export const ClientTableColumns: string[] = [
  'TABLE_HEADERS.FULL_NAME',
  'TABLE_HEADERS.DATE_OF_BIRTH',
  'TABLE_HEADERS.EMAIL',
  'TABLE_HEADERS.PHONE_NUMBER',
  'TABLE_HEADERS.LAST_SEEN_DATE',
  'TABLE_HEADERS.LAST_TRANSACTION_DATE',
  'TABLE_HEADERS.ACCOUNT',
  'TABLE_HEADERS.STATUS',
];
